# Package testing notebook

In [ ]:
from sonnenstund.data.providers.geosphereaustria import _GeoSphereAustria
from sonnenstund.data import Parameter
from datetime import datetime as dt
from shapely.geometry import Point
import logging
import sys

logging.basicConfig(
    stream=sys.stdout, level=logging.INFO, format="%(asctime)s %(message)s"
)  # view logging output

In [2]:
time_from = dt.fromisoformat("2026-01-01")
time_to = dt.fromisoformat("2026-05-16")
location = Point(16.371768383289528, 48.20812384775554)

In [5]:
location_data = _GeoSphereAustria.get_historical_location_data(
    time_from, time_to, location, [Parameter.SUN_HOURS], quality=True
)

2026-05-17 16:26:49,909 Getting historical location data from GeoSphere Austria API for time range 2026-01-01 00:00:00 to 2026-05-16 00:00:00, locations: POINT (16.371768383289528 48.20812384775554), parameters: [<Parameter.SUN_HOURS: 'sun_hours'>], radius: None, quality: True
2026-05-17 16:26:49,910 Finding closest station to location: POINT (16.371768383289528 48.20812384775554)
2026-05-17 16:26:49,910 Finding nearest points to a given location: POINT (16.371768383289528 48.20812384775554)
2026-05-17 16:26:49,911 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.24069 47.54594)
2026-05-17 16:26:49,911 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.13826 47.53278)
2026-05-17 16:26:49,912 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.36694 48.69083)
2026-05-17 16:26:49,913 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.895 48.10889)
2026-05-17 16:26:49,914 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.75844 47.6105)
2026-05-17 16:26:49,914 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.68444 46.62528)
2026-05-17 16:26:49,915 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.13336 47.11056)
2026-05-17 16:26:49,916 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.90361 46.87222)
2026-05-17 16:26:49,917 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.64472 47.62194)
2026-05-17 16:26:49,918 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.93472 47.55333)
2026-05-17 16:26:49,919 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.99333 46.69222)
2026-05-17 16:26:49,920 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.26139 47.40833)
2026-05-17 16:26:49,921 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.22111 47.40667)
2026-05-17 16:26:49,921 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (9.74611 47.49917)
2026-05-17 16:26:49,922 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.51083 47.00722)
2026-05-17 16:26:49,923 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.233611 47.403056)
2026-05-17 16:26:49,923 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.845 48.01278)
2026-05-17 16:26:49,924 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.08286 46.74189)
2026-05-17 16:26:49,925 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.92 47.40417)
2026-05-17 16:26:49,925 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.59333 46.49056)
2026-05-17 16:26:49,926 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.53833 47.85417)
2026-05-17 16:26:49,927 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.45028 48.19583)
2026-05-17 16:26:49,927 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (9.60972 47.27111)
2026-05-17 16:26:49,928 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.64389 47.44417)
2026-05-17 16:26:49,929 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.50639 48.49472)
2026-05-17 16:26:49,930 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.825 48.20422)
2026-05-17 16:26:49,931 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.18556 46.96806)
2026-05-17 16:26:49,931 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.448056 47.08)
2026-05-17 16:26:49,932 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.55917 48.19975)
2026-05-17 16:26:49,932 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.28083 48.03583)
2026-05-17 16:26:49,933 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.035 47.82222)
2026-05-17 16:26:49,933 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.06167 48.60333)
2026-05-17 16:26:49,934 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.74222 47.23694)
2026-05-17 16:26:49,935 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.38425 47.25986)
2026-05-17 16:26:49,935 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.09967 47.495)
2026-05-17 16:26:49,936 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.75814 47.38878)
2026-05-17 16:26:49,936 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.6465 47.00478)
2026-05-17 16:26:49,937 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.75961 47.42126)
2026-05-17 16:26:49,937 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.62222 48.41861)
2026-05-17 16:26:49,938 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.18197 47.22911)
2026-05-17 16:26:49,938 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.31833 46.64833)
2026-05-17 16:26:49,939 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.326667 47.2075)
2026-05-17 16:26:49,939 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.56364 47.14025)
2026-05-17 16:26:49,940 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.11806 48.32389)
2026-05-17 16:26:49,941 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.69722 48.4725)
2026-05-17 16:26:49,941 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.59222 47.07361)
2026-05-17 16:26:49,942 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.55289 46.76739)
2026-05-17 16:26:49,943 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.80639 46.82555)
2026-05-17 16:26:49,943 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.28528 48.29639)
2026-05-17 16:26:49,944 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.03831 48.95464)
2026-05-17 16:26:49,944 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.64556 47.46528)
2026-05-17 16:26:49,945 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.30222 47.78917)
2026-05-17 16:26:49,946 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.10556 47.97722)
2026-05-17 16:26:49,946 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.85139 47.1625)
2026-05-17 16:26:49,947 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.57278 46.80806)
2026-05-17 16:26:49,947 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.03333 47.51111)
2026-05-17 16:26:49,948 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.42472 47.06972)
2026-05-17 16:26:49,948 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.82889 47.94917)
2026-05-17 16:26:49,949 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.02444 46.86694)
2026-05-17 16:26:49,950 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.37167 48.55889)
2026-05-17 16:26:49,950 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.55972 47.24889)
2026-05-17 16:26:49,950 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.19444 46.93528)
2026-05-17 16:26:49,951 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.6375 48.66917)
2026-05-17 16:26:49,951 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.920278 46.938333)
2026-05-17 16:26:49,952 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.90694 47.79028)
2026-05-17 16:26:49,953 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.44083 47.38)
2026-05-17 16:26:49,953 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.02833 48.22417)
2026-05-17 16:26:49,954 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.71528 47.49444)
2026-05-17 16:26:49,955 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.00444 48.56722)
2026-05-17 16:26:49,956 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.99262 47.22353)
2026-05-17 16:26:49,957 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.83694 47.69972)
2026-05-17 16:26:49,958 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.94167 48.76111)
2026-05-17 16:26:49,959 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.62594 47.13492)
2026-05-17 16:26:49,960 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.64844 47.38789)
2026-05-17 16:26:49,961 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.73794 47.32872)
2026-05-17 16:26:49,961 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.46639 47.19861)
2026-05-17 16:26:49,962 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.17542 47.32478)
2026-05-17 16:26:49,963 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.82839 47.63325)
2026-05-17 16:26:49,966 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.20361 48.61778)
2026-05-17 16:26:49,967 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.82806 46.76417)
2026-05-17 16:26:49,968 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.765 46.561389)
2026-05-17 16:26:49,969 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.62269 47.09447)
2026-05-17 16:26:49,970 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.63111 48.19972)
2026-05-17 16:26:49,970 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.48978 47.18211)
2026-05-17 16:26:49,972 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.38556 46.73917)
2026-05-17 16:26:49,973 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.18822 47.12303)
2026-05-17 16:26:49,974 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.80833 47.13306)
2026-05-17 16:26:49,975 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.87389 46.61806)
2026-05-17 16:26:49,976 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.80972 47.94556)
2026-05-17 16:26:49,976 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.28583 46.71861)
2026-05-17 16:26:49,977 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.19083 46.84917)
2026-05-17 16:26:49,978 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.66572 47.85719)
2026-05-17 16:26:49,979 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.35639 48.24861)
2026-05-17 16:26:49,980 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.22944 48.20694)
2026-05-17 16:26:49,982 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.41944 48.125)
2026-05-17 16:26:49,982 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.32611 47.72028)
2026-05-17 16:26:49,984 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.44194 47.74028)
2026-05-17 16:26:49,985 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.67092 48.10542)
2026-05-17 16:26:49,986 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.23147 47.83233)
2026-05-17 16:26:49,987 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.78639 47.29)
2026-05-17 16:26:49,988 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.74689 47.19983)
2026-05-17 16:26:49,989 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (15.22694 46.82167)
2026-05-17 16:26:49,990 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.38917 47.44389)
2026-05-17 16:26:49,990 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.26667 47.13139)
2026-05-17 16:26:49,992 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.31417 46.53111)
2026-05-17 16:26:49,993 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.49694 46.89111)
2026-05-17 16:26:49,994 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.90194 46.67722)
2026-05-17 16:26:49,995 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.77861 47.27083)
2026-05-17 16:26:49,996 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.88944 47.25972)
2026-05-17 16:26:49,996 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.50389 47.24917)
2026-05-17 16:26:49,997 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.69528 47.58444)
2026-05-17 16:26:49,998 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.42358 46.74644)
2026-05-17 16:26:49,998 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.00861 47.78944)
2026-05-17 16:26:49,999 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.64714 47.70619)
2026-05-17 16:26:49,999 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (9.67444 47.31417)
2026-05-17 16:26:50,000 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.71361 48.33778)
2026-05-17 16:26:50,001 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.92889 47.13917)
2026-05-17 16:26:50,001 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.9025 46.95806)
2026-05-17 16:26:50,002 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.66472 47.06861)
2026-05-17 16:26:50,002 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.46611 47.09833)
2026-05-17 16:26:50,003 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (16.228056 47.328056)
2026-05-17 16:26:50,004 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.475 48.21722)
2026-05-17 16:26:50,004 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (12.16278 47.57528)
2026-05-17 16:26:50,005 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.117222 47.88388)
2026-05-17 16:26:50,006 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.05417 47.79111)
2026-05-17 16:26:50,007 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (10.33867 47.25758)
2026-05-17 16:26:50,008 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.90422 47.44678)
2026-05-17 16:26:50,009 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (14.89861 48.70222)
2026-05-17 16:26:50,010 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.16667 46.99194)
2026-05-17 16:26:50,011 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (13.48725 46.7905)
2026-05-17 16:26:50,012 Calculating geodesic distance between two points: POINT (16.371768383289528 48.20812384775554) and POINT (11.70667 47.49944)

In [6]:
location_data.geopandas_df

           date                   geometry sun_hours sun_hours_quality
0    2026-01-01  POINT (16.36694 48.19833)       6.0              high
1    2026-01-02  POINT (16.36694 48.19833)       3.4              high
2    2026-01-03  POINT (16.36694 48.19833)       7.8              high
3    2026-01-04  POINT (16.36694 48.19833)       7.7              high
4    2026-01-05  POINT (16.36694 48.19833)       0.0              high
..          ...                        ...       ...               ...
131  2026-05-12  POINT (16.36694 48.19833)       0.5            medium
132  2026-05-13  POINT (16.36694 48.19833)      13.6            medium
133  2026-05-14  POINT (16.36694 48.19833)       0.6            medium
134  2026-05-15  POINT (16.36694 48.19833)       2.1            medium
135  2026-05-16  POINT (16.36694 48.19833)       0.0            medium

[136 rows x 4 columns]

In [7]:
location_data.df

           date                   geometry sun_hours sun_hours_quality
0    2026-01-01  POINT (16.36694 48.19833)       6.0              high
1    2026-01-02  POINT (16.36694 48.19833)       3.4              high
2    2026-01-03  POINT (16.36694 48.19833)       7.8              high
3    2026-01-04  POINT (16.36694 48.19833)       7.7              high
4    2026-01-05  POINT (16.36694 48.19833)       0.0              high
..          ...                        ...       ...               ...
131  2026-05-12  POINT (16.36694 48.19833)       0.5            medium
132  2026-05-13  POINT (16.36694 48.19833)      13.6            medium
133  2026-05-14  POINT (16.36694 48.19833)       0.6            medium
134  2026-05-15  POINT (16.36694 48.19833)       2.1            medium
135  2026-05-16  POINT (16.36694 48.19833)       0.0            medium

[136 rows x 4 columns]